#!/usr/bin/env python3
"""Synchronize legacy config aliases from canonical codec configs."""

from __future__ import annotations

from pathlib import Path

ALIASES = {
    "config/tinyaya_q8_download_overfit_1sample.toml": "codecs/mimi/configs/tinyaya_mimi_q8_download_overfit_1sample.toml",
    "config/tinyaya_s1_q10_download_overfit_1sample.toml": "codecs/s1_dac/configs/tinyaya_s1_q9_download_overfit_1sample.toml",
}


def _legacy_header(alias_path: str, canonical_path: str) -> str:
    return (
        "# LEGACY ALIAS CONFIG\n"
        f"# alias: {alias_path}\n"
        f"# canonical: {canonical_path}\n"
        "# This file is generated by scripts/dev/sync_config_aliases.py\n\n"
    )


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    updated = 0
    for alias_rel, canonical_rel in ALIASES.items():
        alias_path = repo_root / alias_rel
        canonical_path = repo_root / canonical_rel
        if not canonical_path.exists():
            raise SystemExit(f"missing canonical config: {canonical_path}")

        canonical_body = canonical_path.read_text(encoding="utf-8")
        rendered = _legacy_header(alias_rel, canonical_rel) + canonical_body
        alias_path.parent.mkdir(parents=True, exist_ok=True)
        if not alias_path.exists() or alias_path.read_text(encoding="utf-8") != rendered:
            alias_path.write_text(rendered, encoding="utf-8")
            updated += 1
            print(f"updated {alias_rel} -> {canonical_rel}")

    print(f"done, updated {updated} alias file(s)")


if __name__ == "__main__":
    main()
